[package]
name = "bind9-webadmin"
version = "0.1.0"
edition = "2021"
description = "A web-based management tool for BIND9 DNS server"
license = "MIT"

[dependencies]
actix-web = "4.4.0"
actix-files = "0.6.2"
actix-session = { version = "0.9.0", features = ["cookie-session"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tera = "1.19.0"
chrono = { version = "0.4.31", features = ["serde"] }
bcrypt = "0.14.0"
log = "0.4.20"
env_logger = "0.9.3"
config = "0.13.3"
tokio = { version = "1.32.0", features = ["full"] }
regex = "1.10.2"
duct = "0.13.6"
thiserror = "1.0.48"
anyhow = "1.0.75"
