[package]
name = "bind9-webadmin"
version = "0.1.0"
edition = "2021"
description = "A web-based management tool for BIND9 DNS server"
license = "MIT"

[dependencies]
actix-web = "4.3"
actix-files = "0.6"
actix-session = { version = "0.9", features = ["cookie-session"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1.19"
chrono = { version = "0.4", features = ["serde"] }
bcrypt = "0.14"
log = "0.4"
env_logger = "0.9"
config = "0.13"
tokio = { version = "1.0", features = ["full"] }
regex = "1.7"
duct = "0.13"
thiserror = "1.0"
anyhow = "1.0"
