[server]
host = "0.0.0.0"
port = 8080

[auth]
username = "admin"
# 默认密码是 "admin" - 请在首次登录后立即更改
password_hash = "$2b$12$x0qQZ8U8L6gA7lM7g7lM7eO3GQdJjD6Z6X6Y6W6V6U6T6S6R6Q6P"

[bind9]
config_path = "/etc/bind/named.conf"
zones_path = "/etc/bind/zones/"
service_name = "bind9"

[session]
# 请替换为你自己的32字符以上的随机密钥
secret = "4kQqoPlg3nvUrJbPKmPjqhmJ9QTe2R81"
