[server]
host = "0.0.0.0"
port = 8080

[auth]
username = "admin"
password_hash = "$2b$12$VQ5q6eMNG9aY57o4N9fS4O5wM8JQd3QZ9QZ9QZ9QZ9QZ9QZ9QZ9Q"  # 示例哈希，实际使用时请替换

[bind9]
config_path = "/etc/bind/named.conf"
zones_path = "/var/lib/bind"
service_name = "bind9"

[session]
secret = "yosur-sesfcure-secrset-key-with-dsfdsgat-least-32-charafcters"  # 生产环境请更换为安全密钥
ttl_hours = 24  # 会话有效期24小时

[redis]
url = "redis://127.0.0.1:6379"  # Redis服务器地址，留空则使用Cookie存储
database = 0  # Redis数据库编号
