[server]
address = "0.0.0.0"
port = 8080

[bind9]
service_name = "bind9"
binary_path = "/usr/sbin/named"
config_path = "/etc/bind/named.conf"
zones_dir = "/etc/bind/zones"  # 确保此目录存在或手动创建

[auth]
username = "admin"
# 默认密码是 'admin'，首次登录后请务必更改
password_hash = "$2b$10$VJ5VQvQZJZJZJZJZJZJZ.JZJZJZJZJZJZJZJZJZJZJZJZJZJZJ"
